[package]
name = "rust_builderr_demo_a"
version = "0.1.0"
authors = ["Christopher Sebastian <christopher.sebastian@decatechnologies.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
